#!/usr/bin/env bun
/**
 * Build a single binary with Bun compile.
 *
 * Embeds web assets (CSS, JS) and starter feeds into the binary
 * by generating a bundled entry point that imports them as strings.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const OUT_DIR = join(ROOT, "dist");
const GENERATED = join(ROOT, "src", "_generated-assets.ts");

// Read assets as strings
const css = readFileSync(join(ROOT, "src", "web", "styles.css"), "utf-8");
const js = readFileSync(join(ROOT, "src", "web", "scripts.js"), "utf-8");
const starterFeeds = readFileSync(join(ROOT, "examples", "starter-feeds.json"), "utf-8");

// Generate a module that exports embedded assets
writeFileSync(GENERATED, `// AUTO-GENERATED by scripts/build-binary.ts — do not edit
export const EMBEDDED_CSS = ${JSON.stringify(css)};
export const EMBEDDED_JS = ${JSON.stringify(js)};
export const EMBEDDED_STARTER_FEEDS = ${JSON.stringify(starterFeeds)};
`);

console.log("Generated embedded assets module");

// Read version from package.json
const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf-8"));
const appVersion = pkg.version;

// Compile
mkdirSync(OUT_DIR, { recursive: true });
const bunPath = process.argv[0] || "bun";
const proc = Bun.spawnSync([bunPath, "build", join(ROOT, "src", "cli.ts"), "--compile", `--define`, `__APP_VERSION__="${appVersion}"`, "--outfile", join(OUT_DIR, "feed-curator-bin")], {
  cwd: ROOT,
  stdout: "inherit",
  stderr: "inherit",
});

// Clean up generated file
import("node:fs").then(fs => fs.unlinkSync(GENERATED)).catch(() => {});

if (proc.exitCode !== 0) {
  console.error("Build failed");
  process.exit(1);
}

console.log("Binary built successfully: dist/feed-curator-bin");
