import { getBriefing } from "./article";
import { db } from "./db";
import type { Article, BriefingCluster } from "./types";

export function generateDigestMarkdown(date: string): string | null {
  const briefing = getBriefing(date);
  if (!briefing) return null;

  const clusters: BriefingCluster[] = JSON.parse(briefing.clusters);
  if (clusters.length === 0) return null;

  const lines: string[] = [];
  lines.push(`# Daily Briefing — ${date}`);
  lines.push("");

  for (const cluster of clusters) {
    lines.push(`## ${cluster.topic}`);
    lines.push("");
    lines.push(cluster.summary);
    lines.push("");

    const articles = getArticlesByIds(cluster.article_ids);
    for (const a of articles) {
      const score = a.score !== null ? Math.round(a.score * 100) : "—";
      const title = a.title ?? "(no title)";
      lines.push(`- [${title}](${a.url}) — Score: ${score}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("*Generated by [Feed Curator](https://github.com/rizumita/feed-curator)*");
  lines.push("");

  return lines.join("\n");
}

function getArticlesByIds(ids: number[]): Article[] {
  if (ids.length === 0) return [];
  const placeholders = ids.map(() => "?").join(",");
  return db
    .prepare(`SELECT * FROM articles WHERE id IN (${placeholders})`)
    .all(...ids) as Article[];
}
