import { describe, expect, test, beforeEach } from "vitest";
import { db } from "./db";
import { addFeed, getAllFeeds } from "./feed";
import { addArticle, updateArticleCuration, saveBriefing } from "./article";
import { generateDigestMarkdown } from "./digest";

function clearAll(): void {
  db.prepare("DELETE FROM briefings").run();
  db.prepare("DELETE FROM articles").run();
  db.prepare("DELETE FROM feeds").run();
}

function setupFeed(): number {
  addFeed("https://example.com/rss", "Example Blog");
  return getAllFeeds()[0].id;
}

function getArticleId(url: string): number {
  const row = db.prepare("SELECT id FROM articles WHERE url = ?").get(url) as { id: number };
  return row.id;
}

describe("generateDigestMarkdown", () => {
  beforeEach(clearAll);

  test("returns null when no briefing exists for date", () => {
    expect(generateDigestMarkdown("2026-01-01")).toBeNull();
  });

  test("returns null when briefing has empty clusters", () => {
    saveBriefing("2026-01-01", []);
    expect(generateDigestMarkdown("2026-01-01")).toBeNull();
  });

  test("generates valid Markdown with clusters and articles", () => {
    const feedId = setupFeed();
    addArticle("https://example.com/1", "Article One", "content", feedId);
    addArticle("https://example.com/2", "Article Two", "content", feedId);
    const id1 = getArticleId("https://example.com/1");
    const id2 = getArticleId("https://example.com/2");
    updateArticleCuration(id1, 0.85, "Summary one", "ai");
    updateArticleCuration(id2, 0.72, "Summary two", "dev");

    saveBriefing("2026-01-01", [
      { topic: "AI News", summary: "Latest in AI", article_ids: [id1, id2] },
    ]);

    const md = generateDigestMarkdown("2026-01-01");
    expect(md).not.toBeNull();
    expect(md).toContain("# Daily Briefing — 2026-01-01");
    expect(md).toContain("## AI News");
    expect(md).toContain("Latest in AI");
    expect(md).toContain("[Article One](https://example.com/1) — Score: 85");
    expect(md).toContain("[Article Two](https://example.com/2) — Score: 72");
    expect(md).toContain("Generated by [Feed Curator]");
  });

  test("handles articles with null title", () => {
    const feedId = setupFeed();
    addArticle("https://example.com/notitle", undefined, "content", feedId);
    const id = getArticleId("https://example.com/notitle");
    updateArticleCuration(id, 0.5, "Summary", "misc");

    saveBriefing("2026-01-01", [
      { topic: "Misc", summary: "Miscellaneous", article_ids: [id] },
    ]);

    const md = generateDigestMarkdown("2026-01-01")!;
    expect(md).toContain("(no title)");
  });

  test("escapes Markdown special characters in titles", () => {
    const feedId = setupFeed();
    addArticle("https://example.com/bad", "Title [with] brackets", "content", feedId);
    const id = getArticleId("https://example.com/bad");
    updateArticleCuration(id, 0.9, "Summary", "security");

    saveBriefing("2026-01-01", [
      { topic: "Security", summary: "Security news", article_ids: [id] },
    ]);

    const md = generateDigestMarkdown("2026-01-01")!;
    expect(md).toContain("Title \\[with\\] brackets");
    expect(md).not.toContain("[with]");
  });

  test("handles cluster with missing article IDs gracefully", () => {
    saveBriefing("2026-01-01", [
      { topic: "Ghost", summary: "Articles that don't exist", article_ids: [999, 1000] },
    ]);

    const md = generateDigestMarkdown("2026-01-01")!;
    expect(md).toContain("## Ghost");
    expect(md).toContain("Articles that don't exist");
    expect(md).not.toContain("Score:");
  });

  test("handles multiple clusters", () => {
    const feedId = setupFeed();
    addArticle("https://example.com/1", "First", "content", feedId);
    addArticle("https://example.com/2", "Second", "content", feedId);
    const id1 = getArticleId("https://example.com/1");
    const id2 = getArticleId("https://example.com/2");
    updateArticleCuration(id1, 0.9, "S1", "ai");
    updateArticleCuration(id2, 0.8, "S2", "dev");

    saveBriefing("2026-01-01", [
      { topic: "AI", summary: "AI stuff", article_ids: [id1] },
      { topic: "Dev", summary: "Dev stuff", article_ids: [id2] },
    ]);

    const md = generateDigestMarkdown("2026-01-01")!;
    expect(md).toContain("## AI");
    expect(md).toContain("## Dev");
  });
});
